# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://wankehao.com'
baseurl: ''
title: '万氪号'
description: '选靓号请认准万氪号，我们有：QQ靓号QQ群号B站bilibili靓号UID以及抖音快手号QID！'
permalink: pretty
logo: "https://img.alicdn.com/imgextra/i3/2710706468/O1CN01q7ocuD1xeOV4ATTWN_!!2710706468.jpg"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: 首页
  url: /
- title: Q号
  url: /qqhao/
- title: Q群
  url: /qqqun/
- title: B站
  url: /bilibili/
- title: 其他
  url: /qita/
- title: 资讯
  url: /blog/
- title: 关于
  url: /about/
- title: 联系
  url: /contact/


# Footer nav
navigation_footer:
- title: 返回顶部↑Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: 资讯
    output: true
    description: "客服QQ：19191 08080"
    feature_text:
    feature_image: 

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
